### ISSUE TITLE
운동 결과 화면 심박수 표시

### ISSUE THREAD

**Issue by WhiteHyun** [boostcampwm2023/iOS08-WeTri#16]
## Information

- 담당자: 
- 예상 소요시간: `2`시간
- 우선 순위: `Medium`
- 섹션: iOS

---

- Notion Reference: [운동 결과 화면 심박수 표시](https://geul-woll.notion.site/a265da14cc1c4a15905b6339379b0b12)

**Comment by wonholim** [comment]
제거된 이슈 입니다!
