### ISSUE TITLE
네이버클라우드 VPC 네트워크 구축 및 API 서버, DB 서버 생성

### ISSUE THREAD

**Issue by WhiteHyun** [boostcampwm2023/iOS08-WeTri#32]
## Information

- 담당자: 원호,신정용
- 예상 소요시간: `6`시간
- 우선 순위: `High`
- 섹션: BackEnd

---

- Notion Reference: [네이버클라우드 VPC 네트워크 구축 및 API 서버, DB 서버 생성](https://geul-woll.notion.site/NCP-VPC-c928c99863764a33afe9d694f308bf83)

**Comment by wonholim** [comment]
git repogitory에 대해 변경사항이 없어, 노션에 내용을 담고 이슈를 닫겠습니다!
