### ISSUE TITLE
도메인이 잘작동하는지 수동 배포로 확인해보기

### ISSUE THREAD

**Issue by WhiteHyun** [boostcampwm2023/iOS08-WeTri#43]
## Information

- 담당자: 원호
- 예상 소요시간: `1`시간
- 우선 순위: `Medium`
- 섹션: BackEnd

---

- Notion Reference: [도메인이 잘작동하는지 수동 배포로 확인해보기](https://geul-woll.notion.site/1b334f7c4e53469785cf694a60577847)

**Comment by wonholim** [comment]
수동 배포로 확인했습니다. 이슈 닫겠습니다~
