### ISSUE TITLE
Wetri 인프라 아키텍처 그리기

### ISSUE THREAD

**Issue by WhiteHyun** [boostcampwm2023/iOS08-WeTri#44]
## Information

- 담당자: 원호
- 예상 소요시간: `4`시간
- 우선 순위: `High`
- 섹션: BackEnd

---

- Notion Reference: [Wetri 인프라 아키텍처 그리기](https://geul-woll.notion.site/Wetri-7d6ab85d75774dcd9b1d529f1083c4c8)

**Comment by wonholim** [comment]
Git Repogitory에 변경사항이 없어, 이슈를 닫고 마무리하겠습니다!
