### ISSUE TITLE
mysql DB 수정, 논의

### ISSUE THREAD

**Issue by WhiteHyun** [boostcampwm2023/iOS08-WeTri#46]
## Information

- 담당자: 신정용,원호
- 예상 소요시간: ``시간
- 우선 순위: ``
- 섹션: BackEnd

---

- Notion Reference: [mysql DB 수정, 논의](https://geul-woll.notion.site/mysql-DB-9b21f069f6fe48d2a5c1a32f86f42ed7)

**Comment by sjy982** [comment]
DB 논의 후 수정 완료 했습니다. 이슈 닫을게요
